language: php
sudo: false

php:
    - '5.6'
    - '7.0'
    - '7.1'
    - nightly

matrix:
    fast_finish: true
    include:
        - php: '5.6'
          env: COMPOSER_FLAGS="--prefer-lowest"
        - php: '7.0'
          env: COMPOSER_FLAGS="--prefer-lowest"
        - php: '7.1'
          env: COMPOSER_FLAGS="--prefer-lowest"
    allow_failures:
        - php: nightly

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - composer self-update

before_script:
    - composer install --no-interaction --prefer-dist

script:
    - vendor/bin/phpunit --coverage-text
